export type Product = {
  id: string;
  name: string;
  price: number;
  rating?: string;
  time?: string;
  img?: any;
  desc?: string;
  tag?: string;
  season?: string;
  oldPrice?: number;
  rooms?: string[];
};

const IMG_SUCCULENT = require('@/assets/images/succulent_plant.png');
const IMG_OFFICE = require('@/assets/images/office_plant.png');
const IMG_FIDDLE = require('@/assets/images/fiddle_leaf_fig.png');

const IMAGES = [IMG_SUCCULENT, IMG_OFFICE, IMG_FIDDLE];

export const PRODUCTS: Product[] = [
  // ===== 1-50: Popular Indoor & Ornamental Plants =====
  {
    id: 'plant_1',
    name: 'Tulsi (Holy Basil)',
    price: 49,
    rating: '4.9',
    time: '8 MINS',
    img: IMAGES[0],
    desc: 'Sacred medicinal herb for every Indian home',
    tag: 'Bestseller',
    season: 'All Year',
    rooms: ['Balcony', 'Kitchen', 'Outdoor'],
  },
  {
    id: 'plant_2',
    name: 'Money Plant',
    price: 99,
    rating: '4.8',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Vastu-friendly trailing vine brings prosperity',
    tag: 'Bestseller',
    rooms: ['Living Room', 'Bedroom', 'Bathroom'],
  },
  {
    id: 'plant_3',
    name: 'Aloe Vera',
    price: 129,
    rating: '4.7',
    time: '8 MINS',
    img: IMAGES[2],
    desc: 'Healing succulent with skin care benefits',
    tag: 'Trending',
    oldPrice: 199,
    rooms: ['Kitchen', 'Balcony', 'Bedroom'],
  },
  {
    id: 'plant_4',
    name: 'Ashwagandha',
    price: 149,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Ayurvedic adaptogen herb for stress relief',
    tag: 'Organic',
    season: 'All Year',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_5',
    name: 'Peace Lily',
    price: 349,
    rating: '4.8',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Elegant air-purifying flowering houseplant',
    tag: 'Bestseller',
    oldPrice: 499,
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_6',
    name: 'Snake Plant (Sansevieria)',
    price: 199,
    rating: '4.9',
    time: '8 MINS',
    img: IMAGES[2],
    desc: 'Low-maintenance NASA air purifier plant',
    tag: 'Bestseller',
    rooms: ['Living Room', 'Bedroom', 'Bathroom'],
  },
  {
    id: 'plant_7',
    name: 'Curry Leaf (Kadi Patta)',
    price: 179,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Essential aromatic leaf for Indian cooking',
    season: 'All Year',
    rooms: ['Kitchen', 'Balcony', 'Outdoor'],
  },
  {
    id: 'plant_8',
    name: 'Jasmine (Mogra)',
    price: 249,
    rating: '4.8',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Fragrant white flowers beloved in India',
    tag: 'Bestseller',
    season: 'Summer',
    oldPrice: 349,
    rooms: ['Balcony', 'Outdoor', 'Living Room'],
  },
  {
    id: 'plant_9',
    name: 'Fiddle Leaf Fig',
    price: 799,
    rating: '4.7',
    time: '15 MINS',
    img: IMAGES[2],
    desc: 'Trendy statement plant with violin-shaped leaves',
    tag: 'Trending',
    oldPrice: 1199,
    rooms: ['Living Room', 'Library'],
  },
  {
    id: 'plant_10',
    name: 'Marigold (Genda)',
    price: 39,
    rating: '4.5',
    time: '8 MINS',
    img: IMAGES[0],
    desc: 'Bright festive flowers for puja and decor',
    season: 'Winter',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_11',
    name: 'Dahlia',
    price: 99,
    rating: '4.6',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Stunning multi-petaled ornamental flowers',
    season: 'Winter',
    oldPrice: 149,
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_12',
    name: 'Chrysanthemum (Guldaudi)',
    price: 79,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Colorful autumn blooms perfect for festivals',
    season: 'Winter',
    rooms: ['Balcony', 'Outdoor', 'Living Room'],
  },
  {
    id: 'plant_13',
    name: 'Hibiscus (Gudhal)',
    price: 149,
    rating: '4.7',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Tropical flower used in hair oil and tea',
    tag: 'Trending',
    season: 'All Year',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_14',
    name: 'Desk Plant Assorted',
    price: 199,
    rating: '4.4',
    time: '8 MINS',
    img: IMAGES[1],
    desc: 'Compact green companion for your work desk',
    rooms: ['Living Room', 'Library', 'Bedroom'],
  },
  {
    id: 'plant_15',
    name: 'Spider Plant',
    price: 149,
    rating: '4.6',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Graceful arching leaves purify indoor air',
    oldPrice: 199,
    rooms: ['Living Room', 'Bedroom', 'Bathroom'],
  },
  {
    id: 'plant_16',
    name: 'Pothos Golden',
    price: 99,
    rating: '4.7',
    time: '8 MINS',
    img: IMAGES[0],
    desc: 'Heart-shaped golden variegated trailing vine',
    tag: 'Bestseller',
    rooms: ['Living Room', 'Bedroom', 'Bathroom'],
  },
  {
    id: 'plant_17',
    name: 'ZZ Plant (Zamioculcas)',
    price: 349,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Glossy dark leaves thrive on total neglect',
    oldPrice: 499,
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_18',
    name: 'Rubber Plant (Ficus Elastica)',
    price: 299,
    rating: '4.7',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Bold burgundy leaves make a statement',
    tag: 'Trending',
    rooms: ['Living Room', 'Library'],
  },
  {
    id: 'plant_19',
    name: 'Areca Palm',
    price: 399,
    rating: '4.8',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Natural humidifier with elegant feathery fronds',
    tag: 'Bestseller',
    oldPrice: 599,
    rooms: ['Living Room', 'Bedroom', 'Balcony'],
  },
  {
    id: 'plant_20',
    name: 'Bamboo Palm',
    price: 449,
    rating: '4.6',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Tropical palm ideal for shaded corners',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_21',
    name: 'Boston Fern',
    price: 249,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Lush hanging fern for humid spaces',
    oldPrice: 349,
    rooms: ['Bathroom', 'Balcony', 'Living Room'],
  },
  {
    id: 'plant_22',
    name: "Bird's Nest Fern",
    price: 299,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Wavy rosette fronds love bathroom humidity',
    rooms: ['Bathroom', 'Living Room', 'Bedroom'],
  },
  {
    id: 'plant_23',
    name: 'Jade Plant (Crassula)',
    price: 199,
    rating: '4.7',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Lucky succulent symbolizing wealth and fortune',
    tag: 'Bestseller',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_24',
    name: 'String of Pearls',
    price: 349,
    rating: '4.4',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Cascading bead-like succulent for hanging pots',
    tag: 'Trending',
    oldPrice: 499,
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_25',
    name: 'Echeveria',
    price: 149,
    rating: '4.6',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Rosette succulent with pastel-colored leaves',
    rooms: ['Living Room', 'Balcony', 'Bedroom'],
  },
  {
    id: 'plant_26',
    name: 'Haworthia',
    price: 179,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Compact zebra-striped windowsill succulent',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_27',
    name: 'Calathea Medallion',
    price: 449,
    rating: '4.6',
    time: '15 MINS',
    img: IMAGES[2],
    desc: 'Striking patterned leaves fold at night',
    tag: 'Premium',
    oldPrice: 649,
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_28',
    name: 'Monstera Deliciosa',
    price: 599,
    rating: '4.9',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Iconic Swiss cheese plant for interiors',
    tag: 'Bestseller',
    oldPrice: 899,
    rooms: ['Living Room', 'Library'],
  },
  {
    id: 'plant_29',
    name: 'Philodendron Brasil',
    price: 299,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Vibrant lime and green heart-shaped leaves',
    rooms: ['Living Room', 'Bedroom', 'Bathroom'],
  },
  {
    id: 'plant_30',
    name: 'Dracaena Marginata',
    price: 349,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Slender red-edged leaves on tall canes',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_31',
    name: 'Croton Petra',
    price: 249,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Fiery multicolored foliage brightens any spot',
    oldPrice: 349,
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_32',
    name: 'Dieffenbachia (Dumb Cane)',
    price: 279,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Large cream-splashed tropical foliage plant',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_33',
    name: 'Aglaonema Red',
    price: 399,
    rating: '4.7',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Vibrant red Chinese Evergreen for low light',
    tag: 'Trending',
    oldPrice: 549,
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_34',
    name: 'Anthurium Red',
    price: 449,
    rating: '4.7',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Glossy red heart-shaped exotic flowers',
    tag: 'Premium',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_35',
    name: 'Syngonium Pink',
    price: 249,
    rating: '4.6',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Arrowhead vine with soft pink variegation',
    tag: 'Trending',
    oldPrice: 349,
    rooms: ['Living Room', 'Bedroom', 'Bathroom'],
  },
  {
    id: 'plant_36',
    name: 'Peperomia Watermelon',
    price: 299,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Adorable watermelon-patterned compact leaves',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_37',
    name: 'Ficus Benjamina (Weeping Fig)',
    price: 399,
    rating: '4.4',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Classic indoor tree with drooping branches',
    rooms: ['Living Room', 'Library'],
  },
  {
    id: 'plant_38',
    name: 'Schefflera (Umbrella Plant)',
    price: 349,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Lush umbrella-shaped foliage for corners',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_39',
    name: 'Norfolk Island Pine',
    price: 599,
    rating: '4.4',
    time: '18 MINS',
    img: IMAGES[2],
    desc: 'Indoor Christmas tree alternative for homes',
    tag: 'Premium',
    oldPrice: 849,
    rooms: ['Living Room', 'Library'],
  },
  {
    id: 'plant_40',
    name: 'Ponytail Palm',
    price: 499,
    rating: '4.6',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Quirky bulbous trunk with cascading leaves',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_41',
    name: 'Cast Iron Plant (Aspidistra)',
    price: 349,
    rating: '4.3',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Nearly indestructible plant for dark corners',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_42',
    name: 'Prayer Plant (Maranta)',
    price: 349,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Leaves fold upward like praying hands',
    tag: 'Trending',
    oldPrice: 499,
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_43',
    name: 'Wandering Jew (Tradescantia)',
    price: 129,
    rating: '4.5',
    time: '8 MINS',
    img: IMAGES[0],
    desc: 'Stunning purple trailing vine grows fast',
    rooms: ['Living Room', 'Balcony', 'Bathroom'],
  },
  {
    id: 'plant_44',
    name: 'English Ivy',
    price: 179,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Classic trailing vine purifies indoor air',
    rooms: ['Living Room', 'Bedroom', 'Bathroom'],
  },
  {
    id: 'plant_45',
    name: 'Coleus',
    price: 79,
    rating: '4.5',
    time: '8 MINS',
    img: IMAGES[2],
    desc: 'Vivid multi-colored painted nettle leaves',
    season: 'Monsoon',
    rooms: ['Balcony', 'Outdoor', 'Living Room'],
  },
  {
    id: 'plant_46',
    name: 'Caladium',
    price: 199,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Dramatic heart-shaped pink and white leaves',
    tag: 'Trending',
    season: 'Monsoon',
    oldPrice: 299,
    rooms: ['Living Room', 'Bedroom', 'Balcony'],
  },
  {
    id: 'plant_47',
    name: 'Begonia Rex',
    price: 249,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Metallic patterned foliage in jewel tones',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_48',
    name: 'African Violet (Saintpaulia)',
    price: 199,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Compact flowering plant for windowsills',
    rooms: ['Living Room', 'Bedroom', 'Kitchen'],
  },
  {
    id: 'plant_49',
    name: 'Orchid Phalaenopsis',
    price: 599,
    rating: '4.8',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Elegant moth orchid with lasting blooms',
    tag: 'Premium',
    oldPrice: 899,
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_50',
    name: 'Bromeliad',
    price: 349,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Exotic tropical rosette with vivid bracts',
    rooms: ['Living Room', 'Bedroom', 'Balcony'],
  },

  // ===== 51-100: Outdoor, Flowering, Fruit Trees =====
  {
    id: 'plant_51',
    name: 'Adenium (Desert Rose)',
    price: 299,
    rating: '4.7',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Stunning caudiciform with pink trumpet flowers',
    tag: 'Trending',
    season: 'Summer',
    oldPrice: 449,
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_52',
    name: 'Bougainvillea',
    price: 149,
    rating: '4.7',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Vibrant papery bracts cover thorny vines',
    tag: 'Bestseller',
    season: 'Summer',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_53',
    name: 'Plumeria (Champa)',
    price: 349,
    rating: '4.7',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Heavenly fragrant frangipani temple flower',
    season: 'Summer',
    oldPrice: 499,
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_54',
    name: 'Rose (Desi Gulab)',
    price: 129,
    rating: '4.8',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Classic Indian rose with intoxicating scent',
    tag: 'Bestseller',
    season: 'Winter',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_55',
    name: 'Night Jasmine (Raat Rani)',
    price: 199,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Intensely fragrant blooms open after sunset',
    season: 'All Year',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_56',
    name: 'Parijat (Harsingar)',
    price: 249,
    rating: '4.7',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Sacred night-blooming orange-stemmed flowers',
    tag: 'Rare',
    season: 'Monsoon',
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_57',
    name: 'Chameli (Indian Jasmine)',
    price: 179,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Sweet scented jasmine variety for gardens',
    season: 'Summer',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_58',
    name: 'Rajnigandha (Tuberose)',
    price: 99,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Tall spikes of intensely fragrant flowers',
    season: 'Monsoon',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_59',
    name: 'Sadabahar (Periwinkle)',
    price: 49,
    rating: '4.4',
    time: '8 MINS',
    img: IMAGES[1],
    desc: 'Evergreen bloomer in pink white and purple',
    season: 'All Year',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_60',
    name: 'Gulmohar (Flame Tree)',
    price: 399,
    rating: '4.5',
    time: '20 MINS',
    img: IMAGES[2],
    desc: 'Magnificent canopy of fiery orange flowers',
    season: 'Summer',
    oldPrice: 599,
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_61',
    name: 'Amaltas (Golden Shower)',
    price: 349,
    rating: '4.4',
    time: '20 MINS',
    img: IMAGES[0],
    desc: 'Cascading golden flower clusters in summer',
    season: 'Summer',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_62',
    name: 'Neem (Azadirachta)',
    price: 199,
    rating: '4.7',
    time: '18 MINS',
    img: IMAGES[1],
    desc: 'Medicinal tree with natural pesticide properties',
    tag: 'Organic',
    season: 'All Year',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_63',
    name: 'Peepal (Sacred Fig)',
    price: 149,
    rating: '4.5',
    time: '18 MINS',
    img: IMAGES[2],
    desc: 'Sacred Bodhi tree releases oxygen at night',
    season: 'All Year',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_64',
    name: 'Banyan (Bargad)',
    price: 249,
    rating: '4.4',
    time: '20 MINS',
    img: IMAGES[0],
    desc: 'Majestic national tree with aerial roots',
    season: 'All Year',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_65',
    name: 'Ashoka Tree',
    price: 349,
    rating: '4.5',
    time: '20 MINS',
    img: IMAGES[1],
    desc: 'Evergreen ornamental tree for privacy screens',
    season: 'All Year',
    oldPrice: 499,
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_66',
    name: 'Arjuna Tree',
    price: 299,
    rating: '4.3',
    time: '20 MINS',
    img: IMAGES[2],
    desc: 'Heart-healthy medicinal bark Ayurvedic tree',
    tag: 'Organic',
    season: 'All Year',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_67',
    name: 'Moringa (Drumstick)',
    price: 129,
    rating: '4.7',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Superfood tree packed with vital nutrients',
    tag: 'Organic',
    season: 'All Year',
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_68',
    name: 'Amla (Indian Gooseberry)',
    price: 249,
    rating: '4.6',
    time: '18 MINS',
    img: IMAGES[1],
    desc: 'Vitamin C rich fruit for hair and health',
    season: 'All Year',
    oldPrice: 349,
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_69',
    name: 'Papaya',
    price: 99,
    rating: '4.5',
    time: '15 MINS',
    img: IMAGES[2],
    desc: 'Fast-growing tropical fruit tree for gardens',
    season: 'All Year',
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_70',
    name: 'Guava (Amrud)',
    price: 199,
    rating: '4.7',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Delicious desi fruit plant easy to grow',
    tag: 'Bestseller',
    season: 'All Year',
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_71',
    name: 'Lemon (Nimbu)',
    price: 249,
    rating: '4.8',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Citrus fruit plant perfect for home gardens',
    tag: 'Bestseller',
    season: 'All Year',
    oldPrice: 349,
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_72',
    name: 'Mango (Aam) Grafted',
    price: 499,
    rating: '4.8',
    time: '20 MINS',
    img: IMAGES[2],
    desc: 'King of fruits grafted for early bearing',
    tag: 'Premium',
    season: 'Summer',
    oldPrice: 749,
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_73',
    name: 'Pomegranate (Anar)',
    price: 299,
    rating: '4.6',
    time: '18 MINS',
    img: IMAGES[0],
    desc: 'Ruby red superfruit plant for terrace gardens',
    season: 'All Year',
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_74',
    name: 'Chiku (Sapota)',
    price: 349,
    rating: '4.5',
    time: '18 MINS',
    img: IMAGES[1],
    desc: 'Sweet caramel-flavored tropical fruit tree',
    season: 'All Year',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_75',
    name: 'Banana Plant',
    price: 199,
    rating: '4.5',
    time: '18 MINS',
    img: IMAGES[2],
    desc: 'Tropical fruit herb with large paddle leaves',
    season: 'All Year',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_76',
    name: 'Coconut Palm',
    price: 499,
    rating: '4.4',
    time: '25 MINS',
    img: IMAGES[0],
    desc: 'Iconic tropical palm Kalpavriksha tree of life',
    season: 'All Year',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_77',
    name: 'Jackfruit (Kathal)',
    price: 399,
    rating: '4.3',
    time: '20 MINS',
    img: IMAGES[1],
    desc: 'World largest tree fruit with sweet flesh',
    season: 'All Year',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_78',
    name: 'Custard Apple (Sitaphal)',
    price: 299,
    rating: '4.5',
    time: '18 MINS',
    img: IMAGES[2],
    desc: 'Creamy sweet tropical fruit with seeds',
    season: 'Monsoon',
    oldPrice: 449,
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_79',
    name: 'Jamun (Java Plum)',
    price: 349,
    rating: '4.5',
    time: '20 MINS',
    img: IMAGES[0],
    desc: 'Purple berry fruit helps manage blood sugar',
    season: 'Summer',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_80',
    name: 'Litchi',
    price: 499,
    rating: '4.4',
    time: '25 MINS',
    img: IMAGES[1],
    desc: 'Exotic juicy tropical fruit from North India',
    tag: 'Premium',
    season: 'Summer',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_81',
    name: 'Karonda',
    price: 149,
    rating: '4.2',
    time: '15 MINS',
    img: IMAGES[2],
    desc: 'Tart berry used in pickles and chutneys',
    season: 'Monsoon',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_82',
    name: 'Mulberry (Shahtoot)',
    price: 299,
    rating: '4.5',
    time: '18 MINS',
    img: IMAGES[0],
    desc: 'Sweet berries loved by kids and birds',
    season: 'Spring',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_83',
    name: 'Fig (Anjeer)',
    price: 399,
    rating: '4.6',
    time: '18 MINS',
    img: IMAGES[1],
    desc: 'Ancient fruit tree with honey-sweet figs',
    tag: 'Premium',
    season: 'All Year',
    oldPrice: 599,
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_84',
    name: 'Star Fruit (Kamrakh)',
    price: 349,
    rating: '4.3',
    time: '18 MINS',
    img: IMAGES[2],
    desc: 'Unique star-shaped tangy tropical fruit',
    tag: 'Rare',
    season: 'All Year',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_85',
    name: 'Dragon Fruit',
    price: 299,
    rating: '4.7',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Exotic cactus fruit trending in Indian gardens',
    tag: 'Trending',
    season: 'Summer',
    oldPrice: 449,
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_86',
    name: 'Passion Fruit',
    price: 249,
    rating: '4.5',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Tangy aromatic climber fruit with pulp',
    season: 'Summer',
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_87',
    name: 'Strawberry Plant',
    price: 99,
    rating: '4.6',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Sweet red berries perfect for pots',
    tag: 'Trending',
    season: 'Winter',
    rooms: ['Balcony', 'Kitchen'],
  },
  {
    id: 'plant_88',
    name: 'Blueberry Plant',
    price: 699,
    rating: '4.3',
    time: '20 MINS',
    img: IMAGES[0],
    desc: 'Antioxidant-rich berry bush for cool climates',
    tag: 'Rare',
    season: 'Winter',
    oldPrice: 999,
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_89',
    name: 'Grape Vine',
    price: 249,
    rating: '4.5',
    time: '18 MINS',
    img: IMAGES[1],
    desc: 'Climbing vine yielding sweet and juicy grapes',
    season: 'Spring',
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_90',
    name: 'Kiwi Plant',
    price: 599,
    rating: '4.2',
    time: '20 MINS',
    img: IMAGES[2],
    desc: 'Exotic fuzzy fruit vine for hill climates',
    tag: 'Rare',
    season: 'Spring',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_91',
    name: 'Avocado Plant',
    price: 499,
    rating: '4.3',
    time: '20 MINS',
    img: IMAGES[0],
    desc: 'Trendy superfood tree from seed to fruit',
    tag: 'Trending',
    season: 'All Year',
    oldPrice: 749,
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_92',
    name: 'Apple Ber',
    price: 199,
    rating: '4.6',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Crunchy apple-flavored Indian ber variety',
    season: 'Winter',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_93',
    name: 'Thai Guava (Amrood)',
    price: 249,
    rating: '4.7',
    time: '15 MINS',
    img: IMAGES[2],
    desc: 'Large crispy Thai variety guava for pots',
    tag: 'Bestseller',
    season: 'All Year',
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_94',
    name: 'Peach Plant',
    price: 449,
    rating: '4.3',
    time: '20 MINS',
    img: IMAGES[0],
    desc: 'Soft fuzzy stone fruit for cooler regions',
    season: 'Spring',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_95',
    name: 'Cherry Blossom (Ornamental)',
    price: 999,
    rating: '4.4',
    time: '25 MINS',
    img: IMAGES[1],
    desc: 'Stunning pink spring blooms Japanese sakura',
    tag: 'Rare',
    season: 'Spring',
    oldPrice: 1499,
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_96',
    name: 'Tamarind (Imli)',
    price: 199,
    rating: '4.4',
    time: '18 MINS',
    img: IMAGES[2],
    desc: 'Tangy pod fruit tree for Indian cooking',
    season: 'All Year',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_97',
    name: 'Curry Patta Plant',
    price: 149,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Fragrant curry leaf essential for tempering',
    season: 'All Year',
    rooms: ['Balcony', 'Kitchen', 'Outdoor'],
  },
  {
    id: 'plant_98',
    name: 'Bay Leaf (Tej Patta)',
    price: 199,
    rating: '4.3',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Aromatic culinary leaf for biryanis and stews',
    season: 'All Year',
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_99',
    name: 'Lemongrass',
    price: 79,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Citrusy herb for tea and mosquito repelling',
    tag: 'Organic',
    season: 'Monsoon',
    rooms: ['Balcony', 'Outdoor', 'Kitchen'],
  },
  {
    id: 'plant_100',
    name: 'Cinnamon Plant (Dalchini)',
    price: 349,
    rating: '4.3',
    time: '18 MINS',
    img: IMAGES[0],
    desc: 'Exotic spice tree with fragrant bark',
    tag: 'Rare',
    season: 'All Year',
    oldPrice: 499,
    rooms: ['Outdoor'],
  },

  // ===== 101-150: Herbs, Spices & Vegetables =====
  {
    id: 'plant_101',
    name: 'Mint (Pudina)',
    price: 39,
    rating: '4.6',
    time: '8 MINS',
    img: IMAGES[1],
    desc: 'Fresh cooling herb for chutney and mojitos',
    tag: 'Bestseller',
    season: 'All Year',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_102',
    name: 'Coriander (Dhaniya)',
    price: 29,
    rating: '4.5',
    time: '8 MINS',
    img: IMAGES[2],
    desc: 'Essential Indian garnish herb fast growing',
    season: 'Winter',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_103',
    name: 'Spinach (Palak)',
    price: 29,
    rating: '4.4',
    time: '8 MINS',
    img: IMAGES[0],
    desc: 'Iron-rich leafy green for healthy cooking',
    season: 'Winter',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_104',
    name: 'Methi (Fenugreek)',
    price: 29,
    rating: '4.4',
    time: '8 MINS',
    img: IMAGES[1],
    desc: 'Aromatic leaves for parathas and sabzi',
    season: 'Winter',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_105',
    name: 'Ajwain (Carom Plant)',
    price: 49,
    rating: '4.3',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Digestive herb used in Indian home remedies',
    tag: 'Organic',
    season: 'All Year',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_106',
    name: 'Brahmi',
    price: 99,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Brain-boosting Ayurvedic herb for memory',
    tag: 'Organic',
    rooms: ['Balcony', 'Kitchen'],
  },
  {
    id: 'plant_107',
    name: 'Stevia',
    price: 149,
    rating: '4.4',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Natural zero-calorie sweetener plant at home',
    tag: 'Trending',
    oldPrice: 199,
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_108',
    name: 'Rosemary',
    price: 199,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Aromatic Mediterranean herb for gourmet cooking',
    rooms: ['Kitchen', 'Balcony', 'Living Room'],
  },
  {
    id: 'plant_109',
    name: 'Thyme',
    price: 179,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Tiny fragrant leaves for seasoning and tea',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_110',
    name: 'Oregano',
    price: 149,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Pizza herb you can grow on your windowsill',
    tag: 'Trending',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_111',
    name: 'Italian Basil',
    price: 99,
    rating: '4.6',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Sweet aromatic basil for pesto and pasta',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_112',
    name: 'Sage',
    price: 199,
    rating: '4.3',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Silvery medicinal herb with earthy aroma',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_113',
    name: 'Lavender',
    price: 299,
    rating: '4.7',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Calming purple flowers with soothing fragrance',
    tag: 'Trending',
    oldPrice: 449,
    rooms: ['Bedroom', 'Balcony', 'Living Room'],
  },
  {
    id: 'plant_114',
    name: 'Chamomile',
    price: 179,
    rating: '4.4',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Daisy-like flowers brewed for calming herbal tea',
    season: 'Winter',
    rooms: ['Balcony', 'Kitchen'],
  },
  {
    id: 'plant_115',
    name: 'Lemon Balm',
    price: 149,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Citrus-scented mint relative soothes stress',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_116',
    name: 'Peppermint',
    price: 79,
    rating: '4.5',
    time: '8 MINS',
    img: IMAGES[1],
    desc: 'Strong menthol mint for tea and cooking',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_117',
    name: 'Dill (Suwa)',
    price: 49,
    rating: '4.3',
    time: '8 MINS',
    img: IMAGES[2],
    desc: 'Feathery herb for pickles and raita',
    season: 'Winter',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_118',
    name: 'Parsley',
    price: 79,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Curly garnish herb rich in vitamins',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_119',
    name: 'Chives',
    price: 99,
    rating: '4.3',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Mild onion-flavored herb for garnishing',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_120',
    name: 'Fennel (Saunf)',
    price: 69,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Anise-flavored herb for digestion and cooking',
    season: 'Winter',
    rooms: ['Kitchen', 'Balcony', 'Outdoor'],
  },
  {
    id: 'plant_121',
    name: 'Cardamom (Elaichi)',
    price: 399,
    rating: '4.5',
    time: '18 MINS',
    img: IMAGES[0],
    desc: 'Queen of spices for chai and desserts',
    tag: 'Premium',
    season: 'Monsoon',
    oldPrice: 599,
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_122',
    name: 'Black Pepper Vine',
    price: 299,
    rating: '4.4',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'King of spices climbing vine from Kerala',
    tag: 'Rare',
    season: 'Monsoon',
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_123',
    name: 'Vanilla Plant',
    price: 699,
    rating: '4.3',
    time: '20 MINS',
    img: IMAGES[2],
    desc: 'Exotic orchid vine producing vanilla beans',
    tag: 'Rare',
    season: 'Monsoon',
    oldPrice: 999,
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_124',
    name: 'Saffron (Kesar)',
    price: 499,
    rating: '4.2',
    time: '20 MINS',
    img: IMAGES[0],
    desc: 'Worlds most precious spice crocus bulb',
    tag: 'Rare',
    season: 'Winter',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_125',
    name: 'Turmeric (Haldi)',
    price: 79,
    rating: '4.6',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Golden spice root with anti-inflammatory powers',
    tag: 'Organic',
    season: 'Monsoon',
    rooms: ['Kitchen', 'Balcony', 'Outdoor'],
  },
  {
    id: 'plant_126',
    name: 'Ginger (Adrak)',
    price: 69,
    rating: '4.6',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Spicy rhizome essential in Indian kitchens',
    season: 'Monsoon',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_127',
    name: 'Garlic (Lahsun)',
    price: 49,
    rating: '4.4',
    time: '8 MINS',
    img: IMAGES[0],
    desc: 'Pungent bulb for cooking and immunity',
    season: 'Winter',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_128',
    name: 'Onion Plant',
    price: 39,
    rating: '4.3',
    time: '8 MINS',
    img: IMAGES[1],
    desc: 'Grow your own onions from kitchen sets',
    season: 'Winter',
    rooms: ['Kitchen', 'Balcony', 'Outdoor'],
  },
  {
    id: 'plant_129',
    name: 'Chilli Plant (Mirchi)',
    price: 49,
    rating: '4.6',
    time: '8 MINS',
    img: IMAGES[2],
    desc: 'Fiery green and red chillies for cooking',
    tag: 'Bestseller',
    season: 'All Year',
    rooms: ['Kitchen', 'Balcony', 'Outdoor'],
  },
  {
    id: 'plant_130',
    name: 'Capsicum (Shimla Mirch)',
    price: 69,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Colorful bell peppers for salads and stir-fry',
    season: 'Winter',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_131',
    name: 'Tomato Plant',
    price: 49,
    rating: '4.6',
    time: '8 MINS',
    img: IMAGES[1],
    desc: 'Juicy red tomatoes from your own balcony',
    tag: 'Bestseller',
    season: 'Winter',
    rooms: ['Kitchen', 'Balcony', 'Outdoor'],
  },
  {
    id: 'plant_132',
    name: 'Brinjal (Baingan)',
    price: 39,
    rating: '4.3',
    time: '8 MINS',
    img: IMAGES[2],
    desc: 'Purple eggplant staple in Indian curries',
    season: 'All Year',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_133',
    name: 'Okra (Bhindi)',
    price: 39,
    rating: '4.4',
    time: '8 MINS',
    img: IMAGES[0],
    desc: 'Lady finger vegetable easy to grow at home',
    season: 'Summer',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_134',
    name: 'Bitter Gourd (Karela)',
    price: 39,
    rating: '4.2',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Medicinal bitter vegetable for diabetics',
    season: 'Summer',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_135',
    name: 'Bottle Gourd (Lauki)',
    price: 39,
    rating: '4.3',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Light nutritious gourd climbing vine veggie',
    season: 'Summer',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_136',
    name: 'Ridge Gourd (Tori)',
    price: 39,
    rating: '4.3',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Ridged gourd vine easy summer vegetable',
    season: 'Summer',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_137',
    name: 'Pumpkin (Kaddu)',
    price: 49,
    rating: '4.3',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Large orange cucurbit for sabzi and halwa',
    season: 'Monsoon',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_138',
    name: 'Cucumber (Kheera)',
    price: 39,
    rating: '4.5',
    time: '8 MINS',
    img: IMAGES[2],
    desc: 'Cool refreshing salad veggie easy to grow',
    season: 'Summer',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_139',
    name: 'Watermelon Plant',
    price: 49,
    rating: '4.3',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Juicy summer fruit vine for open spaces',
    season: 'Summer',
    oldPrice: 79,
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_140',
    name: 'Muskmelon Plant',
    price: 49,
    rating: '4.3',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Sweet aromatic melon vine for summer gardens',
    season: 'Summer',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_141',
    name: 'Carrot (Gajar)',
    price: 29,
    rating: '4.4',
    time: '8 MINS',
    img: IMAGES[2],
    desc: 'Orange root vegetable rich in beta-carotene',
    season: 'Winter',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_142',
    name: 'Radish (Mooli)',
    price: 29,
    rating: '4.3',
    time: '8 MINS',
    img: IMAGES[0],
    desc: 'Pungent white root for salad and paratha',
    season: 'Winter',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_143',
    name: 'Beetroot (Chukandar)',
    price: 39,
    rating: '4.4',
    time: '8 MINS',
    img: IMAGES[1],
    desc: 'Deep red root vegetable packed with iron',
    season: 'Winter',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_144',
    name: 'Cauliflower (Gobi)',
    price: 39,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Winter cruciferous vegetable for aloo gobi',
    season: 'Winter',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_145',
    name: 'Cabbage (Patta Gobi)',
    price: 39,
    rating: '4.3',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Crunchy leafy head for salads and sabzi',
    season: 'Winter',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_146',
    name: 'Broccoli',
    price: 79,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Superfood green florets rich in nutrients',
    tag: 'Trending',
    season: 'Winter',
    oldPrice: 119,
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_147',
    name: 'Peas Plant (Matar)',
    price: 39,
    rating: '4.4',
    time: '8 MINS',
    img: IMAGES[2],
    desc: 'Sweet green peas climbing vine for winter',
    season: 'Winter',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_148',
    name: 'Beans (Sem)',
    price: 39,
    rating: '4.3',
    time: '8 MINS',
    img: IMAGES[0],
    desc: 'Protein-rich climbing bean vine for gardens',
    season: 'Winter',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_149',
    name: 'Palak Baby Spinach',
    price: 49,
    rating: '4.5',
    time: '8 MINS',
    img: IMAGES[1],
    desc: 'Tender baby spinach leaves for fresh salads',
    season: 'Winter',
    rooms: ['Kitchen', 'Balcony'],
  },
  {
    id: 'plant_150',
    name: 'Sweet Potato (Shakarkand)',
    price: 59,
    rating: '4.3',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Nutritious orange tuber easy to grow at home',
    season: 'Monsoon',
    rooms: ['Balcony', 'Outdoor'],
  },

  // ===== 151-200: Lucky Bamboo, Bonsai, Ferns, Palms =====
  {
    id: 'plant_151',
    name: 'Lucky Bamboo (2 Layer)',
    price: 249,
    rating: '4.7',
    time: '8 MINS',
    img: IMAGES[0],
    desc: 'Feng shui good luck plant two-tier arrangement',
    tag: 'Bestseller',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_152',
    name: 'Lucky Bamboo (3 Layer)',
    price: 399,
    rating: '4.8',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Three-tier lucky bamboo for happiness and wealth',
    tag: 'Bestseller',
    oldPrice: 549,
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_153',
    name: 'Lucky Bamboo (7 Layer)',
    price: 899,
    rating: '4.8',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Grand seven-layer bamboo for ultimate prosperity',
    tag: 'Premium',
    oldPrice: 1299,
    rooms: ['Living Room', 'Library'],
  },
  {
    id: 'plant_154',
    name: 'Pachira (Money Tree)',
    price: 599,
    rating: '4.6',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Braided trunk money tree attracts fortune',
    tag: 'Trending',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_155',
    name: 'Bonsai Ficus',
    price: 799,
    rating: '4.7',
    time: '18 MINS',
    img: IMAGES[1],
    desc: 'Miniature ficus tree shaped with artistry',
    tag: 'Premium',
    oldPrice: 1199,
    rooms: ['Living Room', 'Library'],
  },
  {
    id: 'plant_156',
    name: 'Bonsai Banyan',
    price: 1299,
    rating: '4.8',
    time: '20 MINS',
    img: IMAGES[2],
    desc: 'Majestic miniature banyan with aerial roots',
    tag: 'Premium',
    oldPrice: 1899,
    rooms: ['Living Room', 'Library'],
  },
  {
    id: 'plant_157',
    name: 'Bonsai Jade',
    price: 699,
    rating: '4.6',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Compact jade bonsai symbolizing good luck',
    rooms: ['Living Room', 'Library', 'Bedroom'],
  },
  {
    id: 'plant_158',
    name: 'Bonsai Carmona',
    price: 899,
    rating: '4.5',
    time: '18 MINS',
    img: IMAGES[1],
    desc: 'Flowering tea tree bonsai with tiny blooms',
    tag: 'Premium',
    oldPrice: 1299,
    rooms: ['Living Room', 'Library'],
  },
  {
    id: 'plant_159',
    name: 'Bonsai Juniper',
    price: 999,
    rating: '4.7',
    time: '18 MINS',
    img: IMAGES[2],
    desc: 'Classic Japanese conifer bonsai evergreen beauty',
    tag: 'Premium',
    rooms: ['Living Room', 'Library', 'Balcony'],
  },
  {
    id: 'plant_160',
    name: 'Bonsai Pomegranate',
    price: 1099,
    rating: '4.6',
    time: '20 MINS',
    img: IMAGES[0],
    desc: 'Fruiting miniature pomegranate bonsai tree',
    tag: 'Rare',
    oldPrice: 1599,
    rooms: ['Living Room', 'Library', 'Balcony'],
  },
  {
    id: 'plant_161',
    name: 'Terrarium Kit Small',
    price: 499,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'DIY glass jar miniature garden ecosystem',
    tag: 'New',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_162',
    name: 'Terrarium Kit Large',
    price: 999,
    rating: '4.6',
    time: '15 MINS',
    img: IMAGES[2],
    desc: 'Premium glass dome terrarium with figurines',
    tag: 'New',
    oldPrice: 1399,
    rooms: ['Living Room', 'Library'],
  },
  {
    id: 'plant_163',
    name: 'Air Plant Tillandsia',
    price: 199,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Soilless wonder plant just mist with water',
    tag: 'Trending',
    rooms: ['Living Room', 'Bedroom', 'Bathroom'],
  },
  {
    id: 'plant_164',
    name: 'Air Plant Xerographica',
    price: 499,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Large silver curly king of air plants',
    tag: 'Rare',
    oldPrice: 699,
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_165',
    name: 'Staghorn Fern',
    price: 449,
    rating: '4.5',
    time: '15 MINS',
    img: IMAGES[2],
    desc: 'Antler-shaped fern mounted on wood plaques',
    tag: 'Rare',
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_166',
    name: 'Maidenhair Fern',
    price: 249,
    rating: '4.4',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Delicate fan-shaped fronds love humidity',
    rooms: ['Bathroom', 'Living Room'],
  },
  {
    id: 'plant_167',
    name: "Bird's Nest Fern Large",
    price: 399,
    rating: '4.5',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Large rosette fern perfect for shaded spots',
    oldPrice: 549,
    rooms: ['Bathroom', 'Living Room', 'Bedroom'],
  },
  {
    id: 'plant_168',
    name: 'Blue Star Fern',
    price: 299,
    rating: '4.4',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Blue-green waxy fronds tolerant of low light',
    rooms: ['Living Room', 'Bedroom', 'Bathroom'],
  },
  {
    id: 'plant_169',
    name: 'Rabbit Foot Fern',
    price: 349,
    rating: '4.3',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Fuzzy rhizomes creep over pot edges',
    tag: 'Rare',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_170',
    name: 'Asparagus Fern',
    price: 179,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Feathery fluffy green trailing fern-like plant',
    rooms: ['Living Room', 'Balcony', 'Bedroom'],
  },
  {
    id: 'plant_171',
    name: 'Sword Fern',
    price: 199,
    rating: '4.3',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Upright sword-shaped fronds for lush greenery',
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_172',
    name: 'Holly Fern',
    price: 249,
    rating: '4.3',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Glossy dark green holly-like fern fronds',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_173',
    name: 'Kangaroo Paw Fern',
    price: 299,
    rating: '4.4',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Unique paw-shaped fronds from Australia',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_174',
    name: 'Button Fern',
    price: 199,
    rating: '4.3',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Tiny round leaflets on arching wiry stems',
    rooms: ['Living Room', 'Bedroom', 'Bathroom'],
  },
  {
    id: 'plant_175',
    name: 'Lemon Button Fern',
    price: 229,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Compact fern with lemony scent when touched',
    rooms: ['Living Room', 'Bedroom', 'Kitchen'],
  },
  {
    id: 'plant_176',
    name: 'Kentia Palm',
    price: 899,
    rating: '4.7',
    time: '20 MINS',
    img: IMAGES[1],
    desc: 'Elegant tall palm for sophisticated interiors',
    tag: 'Premium',
    oldPrice: 1299,
    rooms: ['Living Room', 'Library'],
  },
  {
    id: 'plant_177',
    name: 'Majesty Palm',
    price: 699,
    rating: '4.5',
    time: '18 MINS',
    img: IMAGES[2],
    desc: 'Regal tropical palm with feathery fronds',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_178',
    name: 'Lady Palm (Rhapis)',
    price: 799,
    rating: '4.6',
    time: '18 MINS',
    img: IMAGES[0],
    desc: 'Fan-shaped leaves on slender bamboo-like stems',
    oldPrice: 1099,
    rooms: ['Living Room', 'Library'],
  },
  {
    id: 'plant_179',
    name: 'Fan Palm',
    price: 599,
    rating: '4.4',
    time: '18 MINS',
    img: IMAGES[1],
    desc: 'Broad fan-shaped tropical palm fronds',
    season: 'All Year',
    rooms: ['Living Room', 'Outdoor', 'Balcony'],
  },
  {
    id: 'plant_180',
    name: 'Fishtail Palm',
    price: 649,
    rating: '4.5',
    time: '18 MINS',
    img: IMAGES[2],
    desc: 'Unique fishtail-shaped leaflets on tall stems',
    rooms: ['Living Room', 'Outdoor'],
  },
  {
    id: 'plant_181',
    name: 'Sago Palm (Cycas)',
    price: 499,
    rating: '4.6',
    time: '18 MINS',
    img: IMAGES[0],
    desc: 'Ancient cycad with stiff feathery crown',
    tag: 'Premium',
    rooms: ['Living Room', 'Outdoor', 'Balcony'],
  },
  {
    id: 'plant_182',
    name: "Traveler's Palm",
    price: 1499,
    rating: '4.4',
    time: '25 MINS',
    img: IMAGES[1],
    desc: 'Dramatic fan-shaped banana-like tropical palm',
    tag: 'Rare',
    oldPrice: 2199,
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_183',
    name: 'Date Palm',
    price: 599,
    rating: '4.4',
    time: '20 MINS',
    img: IMAGES[2],
    desc: 'Desert palm producing sweet dates over time',
    season: 'All Year',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_184',
    name: 'Royal Palm',
    price: 999,
    rating: '4.5',
    time: '25 MINS',
    img: IMAGES[0],
    desc: 'Majestic tall palm for grand garden entrances',
    tag: 'Premium',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_185',
    name: 'Bottle Palm',
    price: 1299,
    rating: '4.4',
    time: '25 MINS',
    img: IMAGES[1],
    desc: 'Swollen bottle-shaped trunk ornamental palm',
    tag: 'Rare',
    oldPrice: 1799,
    rooms: ['Outdoor', 'Living Room'],
  },
  {
    id: 'plant_186',
    name: 'Golden Cane Palm',
    price: 449,
    rating: '4.6',
    time: '15 MINS',
    img: IMAGES[2],
    desc: 'Clumping yellow-stemmed palm for privacy screens',
    rooms: ['Living Room', 'Outdoor', 'Balcony'],
  },
  {
    id: 'plant_187',
    name: 'Cat Palm',
    price: 399,
    rating: '4.5',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Compact bushy palm safe for pet homes',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_188',
    name: 'Parlor Palm',
    price: 249,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Victorian-era parlor favorite compact palm',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_189',
    name: 'Pygmy Date Palm',
    price: 549,
    rating: '4.5',
    time: '18 MINS',
    img: IMAGES[2],
    desc: 'Miniature date palm with graceful arching fronds',
    oldPrice: 799,
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_190',
    name: 'Alexander Palm',
    price: 799,
    rating: '4.3',
    time: '20 MINS',
    img: IMAGES[0],
    desc: 'Tall slender self-cleaning Australian palm',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_191',
    name: 'Chinese Fan Palm',
    price: 549,
    rating: '4.4',
    time: '18 MINS',
    img: IMAGES[1],
    desc: 'Large fan-shaped leaves on sturdy trunk',
    rooms: ['Outdoor', 'Living Room'],
  },
  {
    id: 'plant_192',
    name: 'Windmill Palm',
    price: 699,
    rating: '4.3',
    time: '20 MINS',
    img: IMAGES[2],
    desc: 'Cold-hardy palm with hairy fibrous trunk',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_193',
    name: 'Bismarck Palm',
    price: 1999,
    rating: '4.5',
    time: '30 MINS',
    img: IMAGES[0],
    desc: 'Massive silvery blue fan palm showstopper',
    tag: 'Rare',
    oldPrice: 2999,
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_194',
    name: 'Foxtail Palm',
    price: 899,
    rating: '4.5',
    time: '25 MINS',
    img: IMAGES[1],
    desc: 'Plume-like bushy fronds resemble fox tails',
    tag: 'Premium',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_195',
    name: 'Christmas Palm',
    price: 749,
    rating: '4.4',
    time: '20 MINS',
    img: IMAGES[2],
    desc: 'Festive red-fruited dwarf ornamental palm',
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_196',
    name: 'Coconut Palm Mini',
    price: 399,
    rating: '4.3',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Dwarf coconut variety for terrace gardens',
    season: 'All Year',
    rooms: ['Outdoor', 'Balcony'],
  },
  {
    id: 'plant_197',
    name: 'Palmetto',
    price: 549,
    rating: '4.2',
    time: '18 MINS',
    img: IMAGES[1],
    desc: 'Hardy shrubby palm with fan-shaped fronds',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_198',
    name: 'Raffia Palm',
    price: 1199,
    rating: '4.3',
    time: '25 MINS',
    img: IMAGES[2],
    desc: 'Tropical palm with longest leaves in world',
    tag: 'Rare',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_199',
    name: 'Washingtonia Palm',
    price: 699,
    rating: '4.4',
    time: '20 MINS',
    img: IMAGES[0],
    desc: 'Tall desert fan palm iconic in landscapes',
    rooms: ['Outdoor'],
  },
  {
    id: 'plant_200',
    name: 'Licuala Palm',
    price: 899,
    rating: '4.5',
    time: '20 MINS',
    img: IMAGES[1],
    desc: 'Stunning round pleated fan-leaf tropical palm',
    tag: 'Rare',
    oldPrice: 1299,
    rooms: ['Living Room', 'Outdoor'],
  },

  // ===== 201-250: Calatheas, Philodendrons, Hoyas, Rare Plants =====
  {
    id: 'plant_201',
    name: 'Calathea Orbifolia',
    price: 549,
    rating: '4.6',
    time: '15 MINS',
    img: IMAGES[2],
    desc: 'Large round striped leaves prayer plant family',
    tag: 'Trending',
    oldPrice: 799,
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_202',
    name: 'Calathea Lancifolia (Rattlesnake)',
    price: 449,
    rating: '4.5',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Long wavy leaves with dark spots pattern',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_203',
    name: 'Calathea Roseopicta',
    price: 499,
    rating: '4.5',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Rose-painted calathea with pink center markings',
    tag: 'Premium',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_204',
    name: 'Calathea Zebrina',
    price: 449,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Velvety zebra-striped tropical foliage beauty',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_205',
    name: 'Calathea White Fusion',
    price: 699,
    rating: '4.6',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Stunning white and green marbled rare calathea',
    tag: 'Rare',
    oldPrice: 999,
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_206',
    name: 'Maranta Red Prayer Plant',
    price: 349,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Red-veined leaves fold upward each evening',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_207',
    name: 'Maranta Lemon Lime',
    price: 299,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Bright citrus-colored prayer plant variety',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_208',
    name: 'Stromanthe Triostar',
    price: 449,
    rating: '4.6',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Pink white and green variegated showstopper',
    tag: 'Trending',
    oldPrice: 649,
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_209',
    name: 'Ctenanthe Burle-marxii',
    price: 399,
    rating: '4.4',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Fishbone pattern leaves with purple undersides',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_210',
    name: 'Alocasia Polly (African Mask)',
    price: 499,
    rating: '4.6',
    time: '15 MINS',
    img: IMAGES[2],
    desc: 'Dramatic arrowhead leaves with silver veins',
    tag: 'Trending',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_211',
    name: 'Alocasia Zebrina',
    price: 599,
    rating: '4.5',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Zebra-striped stems with large shield leaves',
    tag: 'Rare',
    oldPrice: 899,
    rooms: ['Living Room'],
  },
  {
    id: 'plant_212',
    name: 'Alocasia Frydek',
    price: 649,
    rating: '4.5',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Velvety dark green leaves with white veins',
    tag: 'Rare',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_213',
    name: 'Colocasia Black Magic',
    price: 399,
    rating: '4.5',
    time: '15 MINS',
    img: IMAGES[2],
    desc: 'Dramatic dark purple-black elephant ear leaves',
    tag: 'Trending',
    season: 'Monsoon',
    rooms: ['Outdoor', 'Balcony', 'Living Room'],
  },
  {
    id: 'plant_214',
    name: 'Philodendron Pink Princess',
    price: 1999,
    rating: '4.8',
    time: '20 MINS',
    img: IMAGES[0],
    desc: 'Coveted pink variegated collector philodendron',
    tag: 'Rare',
    oldPrice: 2999,
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_215',
    name: 'Philodendron Birkin',
    price: 599,
    rating: '4.7',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'White pinstripe variegation on dark leaves',
    tag: 'Trending',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_216',
    name: 'Philodendron Micans',
    price: 349,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Velvety bronze heart-shaped trailing leaves',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_217',
    name: 'Philodendron Gloriosum',
    price: 1499,
    rating: '4.7',
    time: '20 MINS',
    img: IMAGES[0],
    desc: 'Massive velvety leaves with glowing white veins',
    tag: 'Rare',
    oldPrice: 2199,
    rooms: ['Living Room'],
  },
  {
    id: 'plant_218',
    name: 'Philodendron Verrucosum',
    price: 1799,
    rating: '4.6',
    time: '20 MINS',
    img: IMAGES[1],
    desc: 'Hairy petioles with velvety iridescent leaves',
    tag: 'Rare',
    rooms: ['Living Room'],
  },
  {
    id: 'plant_219',
    name: 'Monstera Adansonii (Swiss Cheese)',
    price: 399,
    rating: '4.7',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Fenestrated trailing vine with oval holes',
    tag: 'Trending',
    oldPrice: 599,
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_220',
    name: 'Monstera Thai Constellation',
    price: 4999,
    rating: '4.9',
    time: '25 MINS',
    img: IMAGES[0],
    desc: 'Ultra-rare cream speckled monstera collectors dream',
    tag: 'Rare',
    rooms: ['Living Room'],
  },
  {
    id: 'plant_221',
    name: 'Epipremnum Marble Queen',
    price: 199,
    rating: '4.6',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'White and green marbled pothos trailing beauty',
    rooms: ['Living Room', 'Bedroom', 'Bathroom'],
  },
  {
    id: 'plant_222',
    name: 'Epipremnum Neon',
    price: 149,
    rating: '4.6',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Bright chartreuse neon-colored pothos vine',
    tag: 'Trending',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_223',
    name: "Epipremnum N'Joy",
    price: 249,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Compact white and green variegated pothos',
    oldPrice: 349,
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_224',
    name: 'Scindapsus Pictus (Silver Satin)',
    price: 299,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Silvery spotted satin-textured trailing vine',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_225',
    name: 'Scindapsus Treubii Moonlight',
    price: 449,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Silvery moonlit leaves rare collector plant',
    tag: 'Rare',
    oldPrice: 649,
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_226',
    name: 'Hoya Carnosa',
    price: 299,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Waxy porcelain flower clusters fragrant blooms',
    rooms: ['Living Room', 'Bedroom', 'Balcony'],
  },
  {
    id: 'plant_227',
    name: 'Hoya Kerrii (Sweetheart)',
    price: 199,
    rating: '4.7',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Single heart-shaped leaf perfect love gift',
    tag: 'Bestseller',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_228',
    name: 'Hoya Linearis',
    price: 499,
    rating: '4.5',
    time: '15 MINS',
    img: IMAGES[2],
    desc: 'Cascading curtain of soft fuzzy linear leaves',
    tag: 'Rare',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_229',
    name: 'Hoya Pubicalyx',
    price: 349,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Silver-splashed leaves with deep pink flowers',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_230',
    name: 'Hoya Compacta (Hindu Rope)',
    price: 449,
    rating: '4.6',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Twisted curly rope-like waxy leaves drape down',
    tag: 'Premium',
    oldPrice: 649,
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_231',
    name: 'String of Hearts',
    price: 299,
    rating: '4.7',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Delicate trailing hearts romantic hanging plant',
    tag: 'Trending',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_232',
    name: 'String of Turtles',
    price: 399,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Tiny turtle-shell patterned trailing succulent',
    tag: 'Rare',
    oldPrice: 599,
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_233',
    name: 'String of Dolphins',
    price: 449,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Adorable dolphin-shaped leaves cascading down',
    tag: 'Rare',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_234',
    name: 'String of Bananas',
    price: 299,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Banana-shaped leaves on trailing succulent vine',
    rooms: ['Living Room', 'Bedroom', 'Balcony'],
  },
  {
    id: 'plant_235',
    name: 'String of Buttons',
    price: 249,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Stacked button-like leaves on trailing stems',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_236',
    name: 'Senecio Blue Chalk Sticks',
    price: 179,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Powdery blue cylindrical succulent fingers',
    rooms: ['Balcony', 'Living Room'],
  },
  {
    id: 'plant_237',
    name: 'Dischidia Nummularia',
    price: 249,
    rating: '4.3',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Tiny coin-shaped epiphytic trailing plant',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_238',
    name: 'Lipstick Plant (Aeschynanthus)',
    price: 299,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Tubular red flowers emerge from dark calyxes',
    tag: 'Trending',
    rooms: ['Living Room', 'Bedroom', 'Balcony'],
  },
  {
    id: 'plant_239',
    name: 'Goldfish Plant',
    price: 349,
    rating: '4.4',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Orange blooms shaped like leaping goldfish',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_240',
    name: 'Columnea',
    price: 299,
    rating: '4.3',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Trailing gesneriad with fiery tubular flowers',
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_241',
    name: 'Stephanotis (Madagascar Jasmine)',
    price: 449,
    rating: '4.5',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Waxy white fragrant bridal wreath climber',
    tag: 'Premium',
    season: 'Summer',
    oldPrice: 649,
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_242',
    name: 'Dipladenia',
    price: 349,
    rating: '4.4',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Compact mandevilla with trumpet-shaped flowers',
    season: 'Summer',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_243',
    name: 'Mandevilla',
    price: 399,
    rating: '4.5',
    time: '15 MINS',
    img: IMAGES[2],
    desc: 'Vigorous tropical climber with large pink blooms',
    season: 'Summer',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_244',
    name: 'Clematis',
    price: 349,
    rating: '4.4',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Queen of climbers with spectacular star flowers',
    season: 'Spring',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_245',
    name: 'Passiflora (Passion Vine)',
    price: 249,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Exotic intricate flowers on vigorous climber',
    season: 'Summer',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_246',
    name: 'Thunbergia (Black-eyed Susan)',
    price: 149,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Cheerful orange vine with dark eye centers',
    season: 'Summer',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_247',
    name: 'Star Jasmine (Trachelospermum)',
    price: 299,
    rating: '4.6',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Sweetly scented star-shaped white flower climber',
    season: 'Spring',
    oldPrice: 449,
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_248',
    name: 'Hoya Sunrise',
    price: 549,
    rating: '4.5',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Sun-stressed leaves turn gorgeous sunrise red',
    tag: 'Rare',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_249',
    name: 'Pothos Satin',
    price: 249,
    rating: '4.6',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Silvery shimmer on dark velvety green leaves',
    rooms: ['Living Room', 'Bedroom', 'Bathroom'],
  },
  {
    id: 'plant_250',
    name: 'Cebu Blue Pothos',
    price: 349,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Metallic blue-green shimmery elongated leaves',
    tag: 'Trending',
    oldPrice: 499,
    rooms: ['Living Room', 'Bedroom'],
  },

  // ===== 251-300: Cacti, Succulents, Dracaenas, Rare Varieties =====
  {
    id: 'plant_251',
    name: 'Moon Cactus',
    price: 99,
    rating: '4.5',
    time: '8 MINS',
    img: IMAGES[1],
    desc: 'Colorful grafted cactus in neon shades',
    tag: 'Bestseller',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_252',
    name: 'Bunny Ear Cactus',
    price: 149,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Adorable ear-shaped pads with fine glochids',
    rooms: ['Living Room', 'Bedroom', 'Balcony'],
  },
  {
    id: 'plant_253',
    name: 'Old Man Cactus',
    price: 199,
    rating: '4.3',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Fuzzy white-haired columnar cactus character',
    tag: 'Rare',
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_254',
    name: 'Star Cactus',
    price: 179,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Compact star-shaped ribbed desert beauty',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_255',
    name: 'Brain Cactus',
    price: 249,
    rating: '4.4',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Crested wavy growth resembling a brain shape',
    tag: 'Rare',
    oldPrice: 349,
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_256',
    name: 'Totem Pole Cactus',
    price: 349,
    rating: '4.3',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Smooth spineless columnar cactus sculpture',
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_257',
    name: 'Fairy Castle Cactus',
    price: 149,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Turret-shaped clusters like miniature castles',
    tag: 'Bestseller',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_258',
    name: 'Barrel Cactus',
    price: 299,
    rating: '4.3',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Round ribbed desert cactus with golden spines',
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_259',
    name: 'Christmas Cactus',
    price: 199,
    rating: '4.6',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Holiday bloomer with pink tubular flowers',
    season: 'Winter',
    oldPrice: 299,
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_260',
    name: 'Easter Cactus',
    price: 199,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Spring blooming cactus with daisy-like flowers',
    season: 'Spring',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_261',
    name: 'Euphorbia Trigona (African Milk Tree)',
    price: 299,
    rating: '4.4',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Tall columnar succulent with tiny leaves',
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_262',
    name: 'Euphorbia Milii (Crown of Thorns)',
    price: 149,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Thorny succulent with year-round tiny flowers',
    season: 'All Year',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_263',
    name: 'Euphorbia Tirucalli (Pencil Cactus)',
    price: 249,
    rating: '4.3',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Pencil-thin green sticks on branching stems',
    oldPrice: 349,
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_264',
    name: 'Kalanchoe',
    price: 99,
    rating: '4.5',
    time: '8 MINS',
    img: IMAGES[2],
    desc: 'Cheerful clusters of tiny colorful flowers',
    season: 'Winter',
    rooms: ['Living Room', 'Balcony', 'Bedroom'],
  },
  {
    id: 'plant_265',
    name: 'Kalanchoe Mother of Thousands',
    price: 129,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Fascinating plantlets grow along leaf edges',
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_266',
    name: 'Sempervivum (Hens and Chicks)',
    price: 99,
    rating: '4.5',
    time: '8 MINS',
    img: IMAGES[1],
    desc: 'Hardy rosette succulent multiplies prolifically',
    rooms: ['Balcony', 'Outdoor', 'Living Room'],
  },
  {
    id: 'plant_267',
    name: 'Sedum Burrito (Baby Donkey Tail)',
    price: 199,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Plump trailing bead-like succulent for hanging',
    oldPrice: 299,
    rooms: ['Living Room', 'Bedroom', 'Balcony'],
  },
  {
    id: 'plant_268',
    name: "Sedum Morganianum (Donkey's Tail)",
    price: 249,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Long trailing succulent tails for hanging baskets',
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_269',
    name: 'Lithops (Living Stones)',
    price: 149,
    rating: '4.3',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Stone-mimicking succulents from South Africa',
    tag: 'Rare',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_270',
    name: 'Crassula Ovata (Jade)',
    price: 179,
    rating: '4.6',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Thick fleshy oval leaves on woody stems',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_271',
    name: "Crassula Buddha's Temple",
    price: 349,
    rating: '4.4',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Architectural stacked leaves form temple columns',
    tag: 'Rare',
    oldPrice: 499,
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_272',
    name: 'Gasteria',
    price: 149,
    rating: '4.3',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Tongue-shaped spotted succulent for low light',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_273',
    name: 'Aloe Haworthia Hybrid (Alworthia)',
    price: 199,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Compact hybrid combining best of both genera',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_274',
    name: 'Graptoveria',
    price: 149,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Chunky pastel rosette hybrid succulent beauty',
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_275',
    name: 'Pachyveria',
    price: 179,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Thick-leaved hybrid succulent in soft colors',
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_276',
    name: 'Aeonium Schwarzkopf (Black Rose)',
    price: 349,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Dramatic near-black rosettes on branching stems',
    tag: 'Premium',
    oldPrice: 499,
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_277',
    name: 'Agave Attenuata',
    price: 399,
    rating: '4.4',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Spineless soft-tipped blue-green agave rosette',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_278',
    name: 'Agave Blue Glow',
    price: 499,
    rating: '4.5',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Compact blue agave with glowing red margins',
    tag: 'Premium',
    rooms: ['Balcony', 'Outdoor'],
  },
  {
    id: 'plant_279',
    name: 'Yucca Elephantipes',
    price: 449,
    rating: '4.4',
    time: '15 MINS',
    img: IMAGES[2],
    desc: 'Spineless yucca with sword-shaped leaves indoors',
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_280',
    name: 'Sansevieria Moonshine',
    price: 349,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Pale silvery-green moonlit snake plant variety',
    tag: 'Trending',
    oldPrice: 499,
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_281',
    name: 'Sansevieria Cylindrica',
    price: 299,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Round cylindrical spear-shaped snake plant',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_282',
    name: 'Sansevieria Fernwood',
    price: 249,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Slender tiger-striped cylindrical snake plant',
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_283',
    name: 'Sansevieria Whale Fin',
    price: 599,
    rating: '4.6',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Single massive paddle-shaped mottled leaf',
    tag: 'Rare',
    oldPrice: 899,
    rooms: ['Living Room'],
  },
  {
    id: 'plant_284',
    name: 'Zamioculcas Raven (Black ZZ)',
    price: 499,
    rating: '4.7',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Jet-black glossy foliage dramatic dark beauty',
    tag: 'Trending',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_285',
    name: 'Dracaena Compacta',
    price: 399,
    rating: '4.4',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Dense compact dark green rosettes on thick cane',
    rooms: ['Living Room', 'Library'],
  },
  {
    id: 'plant_286',
    name: 'Dracaena Lemon Lime',
    price: 349,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Bright neon-striped leaves on upright canes',
    oldPrice: 499,
    rooms: ['Living Room', 'Bedroom'],
  },
  {
    id: 'plant_287',
    name: 'Dracaena Warneckii',
    price: 349,
    rating: '4.4',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'White-striped sword leaves on sturdy canes',
    rooms: ['Living Room', 'Library'],
  },
  {
    id: 'plant_288',
    name: 'Dracaena Song of India',
    price: 399,
    rating: '4.5',
    time: '15 MINS',
    img: IMAGES[2],
    desc: 'Golden-edged reflexed leaves on graceful stems',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_289',
    name: 'Cordyline Red Star',
    price: 349,
    rating: '4.4',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Deep burgundy-red spiky fountain-like foliage',
    season: 'All Year',
    rooms: ['Living Room', 'Balcony', 'Outdoor'],
  },
  {
    id: 'plant_290',
    name: 'Cordyline Fruticosa',
    price: 299,
    rating: '4.4',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Colorful tropical leaves in reds and pinks',
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_291',
    name: 'Ti Plant',
    price: 249,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Good luck Hawaiian plant with vibrant leaves',
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_292',
    name: 'Croton Gold Dust',
    price: 199,
    rating: '4.3',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Green leaves speckled with bright gold dots',
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_293',
    name: 'Croton Mammy',
    price: 249,
    rating: '4.4',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Twisted multicolor corkscrew-leaved croton beauty',
    oldPrice: 349,
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_294',
    name: 'Schefflera Arboricola (Dwarf Umbrella)',
    price: 249,
    rating: '4.4',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Compact umbrella plant for tabletops and desks',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_295',
    name: 'Polyscias Fabian',
    price: 499,
    rating: '4.5',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Round purple-backed leaves on thick trunk',
    tag: 'Premium',
    rooms: ['Living Room', 'Library'],
  },
  {
    id: 'plant_296',
    name: 'Polyscias Ming (Ming Aralia)',
    price: 449,
    rating: '4.4',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Lacy feathery foliage on elegant twisted trunk',
    oldPrice: 649,
    rooms: ['Living Room', 'Library'],
  },
  {
    id: 'plant_297',
    name: 'Fatshedera (Tree Ivy)',
    price: 349,
    rating: '4.3',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Hybrid of fatsia and ivy versatile climber',
    rooms: ['Living Room', 'Balcony'],
  },
  {
    id: 'plant_298',
    name: 'Fatsia Japonica',
    price: 399,
    rating: '4.4',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Bold glossy palmate leaves for shaded areas',
    rooms: ['Living Room', 'Balcony', 'Outdoor'],
  },
  {
    id: 'plant_299',
    name: 'Aspidistra Elatior (Cast Iron)',
    price: 349,
    rating: '4.3',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Virtually indestructible dark-lover houseplant',
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },
  {
    id: 'plant_300',
    name: 'Chinese Evergreen Silver Queen',
    price: 349,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[2],
    desc: 'Silver-patterned low-light champion aglaonema',
    tag: 'Bestseller',
    oldPrice: 499,
    rooms: ['Living Room', 'Bedroom', 'Library'],
  },

  // ===== TOOLS =====
  {
    id: 'tool_shears',
    name: 'Pruning Shears',
    price: 249,
    rating: '4.6',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Sharp bypass shears for clean plant cuts',
    tag: 'Bestseller',
  },
  {
    id: 'tool_gloves',
    name: 'Gardening Gloves',
    price: 149,
    rating: '4.5',
    time: '8 MINS',
    img: IMAGES[1],
    desc: 'Thorn-proof breathable gloves for safe gardening',
  },
  {
    id: 'tool_can',
    name: 'Watering Can 1.5L',
    price: 299,
    rating: '4.7',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Long-spout watering can for precise pouring',
    tag: 'Bestseller',
    oldPrice: 399,
  },
  {
    id: 'tool_bottle',
    name: 'Spray Bottle 500ml',
    price: 99,
    rating: '4.4',
    time: '8 MINS',
    img: IMAGES[0],
    desc: 'Fine mist sprayer for foliar feeding and misting',
  },
  {
    id: 'tool_trowel',
    name: 'Gardening Trowel',
    price: 199,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Sturdy hand trowel for digging and transplanting',
  },
  {
    id: 'tool_fork',
    name: 'Hand Fork',
    price: 179,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Three-prong fork for loosening and aerating soil',
  },
  {
    id: 'tool_rake',
    name: 'Garden Rake',
    price: 349,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Durable metal rake for leveling and clearing',
    oldPrice: 499,
  },
  {
    id: 'tool_hose',
    name: 'Garden Hose 10m',
    price: 899,
    rating: '4.6',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Flexible ten-meter hose with adjustable nozzle',
    tag: 'Bestseller',
    oldPrice: 1199,
  },
  {
    id: 'tool_pot_s',
    name: 'Ceramic Pot Small',
    price: 249,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Handcrafted small ceramic pot with drainage hole',
  },
  {
    id: 'tool_pot_m',
    name: 'Ceramic Pot Medium',
    price: 449,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Beautiful medium glazed ceramic planter pot',
    tag: 'Trending',
    oldPrice: 599,
  },
  {
    id: 'tool_pot_l',
    name: 'Ceramic Pot Large',
    price: 699,
    rating: '4.6',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Premium large ceramic pot for floor plants',
    tag: 'Premium',
    oldPrice: 999,
  },
  {
    id: 'tool_saucer',
    name: 'Drip Saucer Set (5 pcs)',
    price: 149,
    rating: '4.3',
    time: '8 MINS',
    img: IMAGES[2],
    desc: 'Set of five drip trays to protect surfaces',
  },
  {
    id: 'tool_soil_meter',
    name: 'Soil Moisture Meter',
    price: 399,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Instant reading probe for soil moisture levels',
    tag: 'Trending',
  },
  {
    id: 'tool_grow_light',
    name: 'LED Grow Light',
    price: 1299,
    rating: '4.7',
    time: '15 MINS',
    img: IMAGES[1],
    desc: 'Full-spectrum LED light for indoor plant growth',
    tag: 'Premium',
    oldPrice: 1799,
  },

  // ===== PESTICIDES & CARE =====
  {
    id: 'care_neem',
    name: 'Neem Oil Spray 200ml',
    price: 149,
    rating: '4.6',
    time: '8 MINS',
    img: IMAGES[2],
    desc: 'Organic neem oil for pest and fungus control',
    tag: 'Organic',
  },
  {
    id: 'care_fungi',
    name: 'Fungicide Powder 100g',
    price: 129,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Broad-spectrum fungicide for root rot prevention',
  },
  {
    id: 'care_insect',
    name: 'Insecticide Spray 250ml',
    price: 199,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Effective spray to kill aphids and whiteflies',
    oldPrice: 279,
  },
  {
    id: 'care_root',
    name: 'Root Hormone Gel 50ml',
    price: 179,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Promotes fast root development in cuttings',
    tag: 'Trending',
  },
  {
    id: 'care_potting',
    name: 'Premium Potting Mix 5kg',
    price: 249,
    rating: '4.7',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Well-draining nutrient-rich soil mix for plants',
    tag: 'Bestseller',
    oldPrice: 349,
  },
  {
    id: 'care_copper',
    name: 'Copper Fungicide 100g',
    price: 219,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Copper-based fungicide for blight and mildew',
  },
  {
    id: 'care_sulphur',
    name: 'Sulphur Dust 200g',
    price: 149,
    rating: '4.3',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Natural sulphur powder for fungal disease control',
    tag: 'Organic',
  },
  {
    id: 'care_bio',
    name: 'Bio Pesticide 250ml',
    price: 279,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Eco-friendly biological pest control solution',
    tag: 'Organic',
    oldPrice: 399,
  },
  {
    id: 'care_sticky',
    name: 'Yellow Sticky Traps (20 pcs)',
    price: 99,
    rating: '4.4',
    time: '8 MINS',
    img: IMAGES[1],
    desc: 'Non-toxic sticky traps for flying insect pests',
  },
  {
    id: 'care_snail',
    name: 'Snail & Slug Bait 250g',
    price: 189,
    rating: '4.3',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Pet-safe bait pellets to deter snails slugs',
  },
  {
    id: 'care_aphid',
    name: 'Aphid Spray 200ml',
    price: 169,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Targeted spray to eliminate aphid infestations',
  },
  {
    id: 'care_mite',
    name: 'Mite Control 200ml',
    price: 229,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Effective miticide for spider mite outbreaks',
    oldPrice: 329,
  },
  {
    id: 'care_mealy',
    name: 'Mealybug Killer 200ml',
    price: 199,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Contact spray to kill mealybugs on contact',
  },
  {
    id: 'care_rooting',
    name: 'Rooting Powder 50g',
    price: 129,
    rating: '4.5',
    time: '8 MINS',
    img: IMAGES[0],
    desc: 'Powdered rooting hormone for stem cuttings',
  },
  {
    id: 'care_moss',
    name: 'Sphagnum Moss 500g',
    price: 249,
    rating: '4.6',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Premium dried moss for propagation and aerials',
    tag: 'Trending',
  },

  // ===== FERTILIZERS =====
  {
    id: 'fert_npk',
    name: 'NPK 19-19-19 Fertilizer 1kg',
    price: 199,
    rating: '4.6',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Balanced all-purpose plant growth fertilizer',
    tag: 'Bestseller',
  },
  {
    id: 'fert_vermi',
    name: 'Vermicompost 5kg',
    price: 199,
    rating: '4.7',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Organic worm-castings compost for rich soil',
    tag: 'Organic',
    oldPrice: 299,
  },
  {
    id: 'fert_bone',
    name: 'Bone Meal 1kg',
    price: 149,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Phosphorus-rich organic fertilizer for blooms',
    tag: 'Organic',
  },
  {
    id: 'fert_seaweed',
    name: 'Seaweed Extract 500ml',
    price: 249,
    rating: '4.6',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Liquid seaweed tonic for root and leaf health',
    tag: 'Organic',
  },
  {
    id: 'fert_cow',
    name: 'Cow Dung Manure 5kg',
    price: 99,
    rating: '4.5',
    time: '12 MINS',
    img: IMAGES[0],
    desc: 'Traditional organic manure for soil enrichment',
    tag: 'Organic',
  },
  {
    id: 'fert_mustard',
    name: 'Mustard Cake Powder 1kg',
    price: 129,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Nitrogen-rich organic cake fertilizer for plants',
    tag: 'Organic',
  },
  {
    id: 'fert_epsom',
    name: 'Epsom Salt 500g',
    price: 79,
    rating: '4.5',
    time: '8 MINS',
    img: IMAGES[2],
    desc: 'Magnesium sulfate for greener healthier leaves',
  },
  {
    id: 'fert_fish',
    name: 'Fish Emulsion 500ml',
    price: 199,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'Organic liquid fish fertilizer boosts growth',
    tag: 'Organic',
    oldPrice: 279,
  },
  {
    id: 'fert_humic',
    name: 'Humic Acid 500g',
    price: 249,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[1],
    desc: 'Soil conditioner improves nutrient absorption',
  },
  {
    id: 'fert_micro',
    name: 'Micronutrient Mix 250g',
    price: 179,
    rating: '4.4',
    time: '10 MINS',
    img: IMAGES[2],
    desc: 'Essential trace elements for deficiency correction',
  },
  {
    id: 'fert_bloom',
    name: 'Bloom Booster 250g',
    price: 219,
    rating: '4.5',
    time: '10 MINS',
    img: IMAGES[0],
    desc: 'High-phosphorus formula for abundant flowering',
    tag: 'Trending',
    oldPrice: 299,
  },
  {
    id: 'fert_coco',
    name: 'Cocopeat Block 5kg',
    price: 149,
    rating: '4.6',
    time: '12 MINS',
    img: IMAGES[1],
    desc: 'Compressed coconut coir pith for soilless growing',
    tag: 'Bestseller',
  },
  {
    id: 'fert_perlite',
    name: 'Perlite 1L',
    price: 129,
    rating: '4.5',
    time: '8 MINS',
    img: IMAGES[2],
    desc: 'Volcanic mineral for soil aeration and drainage',
  },
  {
    id: 'fert_compost',
    name: 'Kitchen Compost Bin',
    price: 599,
    rating: '4.4',
    time: '15 MINS',
    img: IMAGES[0],
    desc: 'Compact bin to compost kitchen waste at home',
    tag: 'New',
    oldPrice: 849,
  },
];

export const getProductById = (id: string): Product | undefined => {
  return PRODUCTS.find((p) => p.id === id);
};
